[package]
name = "chumsky"
version = "0.8.0"
description = "A parser library for humans with powerful error recovery"
authors = ["Joshua Barretto <joshua.s.barretto@gmail.com>", "Elijah Hartvigsen <elijah.reed@hartvigsen.xyz", "Jakob Wiesmore <runetynan@gmail.com>"]
repository = "https://github.com/zesterer/chumsky"
license = "MIT"
keywords = ["parser", "combinator", "token", "language", "syntax"]
categories = ["parsing", "text-processing"]
edition = "2018"
exclude = [
    "/misc/*",
	"/benches/*",
]

[features]
default = ["std", "spill-stack", "memoization"]
# Integrate with the standard library
std = []
# Enable nightly-only features like better compiler diagnostics and a Parser impl for ! (the never type)
nightly = []
# Allows deeper recursion by dynamically spilling stack state on to the heap
spill-stack = ["stacker", "std"]
# Allows parser memoisation, speeding up heavily back-tracking parsers and allowing left recursion
memoization = []

[dependencies]
hashbrown = "0.13"
stacker = { version = "0.1", optional = true }
# Enables regex combinators
regex = { version = "1.7", optional = true }

[dev-dependencies]
ariadne = "0.1.5"
pom = "3.2"
nom = "7.1"
serde_json = { version = "1.0", features = ["preserve_order"] }
criterion = "0.4.0"
pest = "2.5"
pest_derive = "2.5"
sn = "0.1"
logos = "0.12"

[[bench]]
name = "json"
harness = false

[[bench]]
name = "lex"
harness = false

[[bench]]
name = "parser"
harness = false

[[bench]]
name = "backtrack"
harness = false
